-- MySQL Script generated by MySQL Workbench
-- Thu Sep 15 12:31:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Video_Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Video_Data` (
  `videoID` INT UNSIGNED NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL,
  `year_released` INT NOT NULL,
  `Director` VARCHAR(100) NULL,
  PRIMARY KEY (`videoID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer_Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer_Data` (
  `customerID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(100) NULL,
  `LastName` VARCHAR(100) NULL,
  `BirthDate` DATE NULL,
  `Address` VARCHAR(100) NULL,
  PRIMARY KEY (`customerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rental_Info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rental_Info` (
  `videoID` INT UNSIGNED NOT NULL,
  `RentalDate` DATE NOT NULL,
  `ReturnDate` DATE NULL,
  `RentalFee` DECIMAL(10,2) NULL,
  `LateFee` DECIMAL(10,2) NULL,
  `customerID` INT UNSIGNED NULL,
  `rentalID` INT NOT NULL AUTO_INCREMENT,
  `dueDate` DATE NOT NULL,
  PRIMARY KEY (`rentalID`),
  INDEX `customerID_idx` (`videoID` ASC) VISIBLE,
  CONSTRAINT `customerID`
    FOREIGN KEY (`videoID`)
    REFERENCES `mydb`.`Customer_Data` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `videoID`
    FOREIGN KEY (`videoID`)
    REFERENCES `mydb`.`Video_Data` (`videoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
